// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01/07/2025, 12:31:22
const configMerger = require("D:/Website/Introsite/intro-website/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
(() => {const cfg=configMerger(undefined, require("./../tailwind.config.js"));cfg.content = cfg.purge;;return cfg;})()
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Website/Introsite/intro-website/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","D:/Website/Introsite/intro-website/layouts/**/*.{vue,js,mjs}","D:/Website/Introsite/intro-website/pages/**/*.{vue,js,mjs}","D:/Website/Introsite/intro-website/composables/**/*.{js,ts,mjs}","D:/Website/Introsite/intro-website/utils/**/*.{js,ts,mjs}","D:/Website/Introsite/intro-website/{A,a}pp.{vue,js,mjs}","D:/Website/Introsite/intro-website/{E,e}rror.{vue,js,mjs}","D:/Website/Introsite/intro-website/app.config.{js,ts,mjs}"] }));

module.exports = config
