// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26-6-2024 14:08:24
const configMerger = require("/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
(() => {const cfg=configMerger(undefined, require("./../tailwind.config.js"));cfg.content = cfg.purge;;return cfg;})()
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/layouts/**/*.{vue,js,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/pages/**/*.{vue,js,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/composables/**/*.{js,ts,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/utils/**/*.{js,ts,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/{A,a}pp.{vue,js,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/{E,e}rror.{vue,js,mjs}","/Users/bartverhaegh/code/rozenlicht/simonstevin-intro/app.config.{js,ts,mjs}"] }));

module.exports = config
